language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  #- "2.7"
  #- "3.5"
  #- "3.6"
  - "3.7"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Creating conda environment using envs/bioinfo-notebook.txt
  - conda create --name bioinfo-notebook-explicit --file envs/bioinfo-notebook.txt
  - conda activate bioinfo-notebook-explicit
  - conda deactivate

  # Creating conda environment using envs/bioinfo-notebook.yml
  - conda env create --name bioinfo-notebook-yml --file envs/bioinfo-notebook.yml
  - conda activate bioinfo-notebook-yml
  - conda deactivate
  
  # Creating conda environment using envs/augustus.yml
  - conda env create --name augustus-yml --file envs/augustus.yml
  - conda activate augustus-yml
  - conda deactivate

  # Creating conda environment using envs/orthofinder.yml
  - conda env create --name orthofinder-yml --file envs/orthofinder.yml
  - conda activate orthofinder-yml
  - conda deactivate
  
script:
  # Confirming that programs work in conda environments
  # bioinfo-notebook-explicit
  - conda activate bioinfo-notebook-explicit
  - bowtie2 --version
  - samtools --version
  - fastq-dump --version
  - conda deactivate
  
  # bioinfo-notebook-yml
  - conda activate bioinfo-notebook-yml
  - bowtie2 --version
  - samtools --version
  - fastq-dump --version
  - conda deactivate
  
  # augustus-yml
  - conda activate augustus-yml
  - augustus --help
  - conda deactivate
  
  # orthofinder-yml
  - conda activate orthofinder-yml
  - orthofinder --help
  - conda deactivate
