remote_theme: pmarsceill/just-the-docs
title: Bioinformatics Notebook
# logo: assets/bioinfo-notebook_logo.svg
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "Bioinformatics Notebook on GitHub":
    - "//github.com/rnnh/bioinfo-notebook"
heading_anchors: true
